/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Pillar = IDL.Record({
  'id' : IDL.Nat,
  'mandate' : IDL.Text,
  'operationalModel' : IDL.Text,
  'name' : IDL.Text,
  'strategicRole' : IDL.Text,
  'governanceNote' : IDL.Text,
  'initiatives' : IDL.Text,
  'futureDirection' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const CollaborationRequest = IDL.Record({
  'id' : IDL.Nat,
  'pathway' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const FeedEntry = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'domain' : IDL.Text,
  'summary' : IDL.Text,
  'isFeatured' : IDL.Bool,
  'timestamp' : IDL.Int,
  'isPublic' : IDL.Bool,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createFeed' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Bool, IDL.Bool],
      [],
      [],
    ),
  'deleteFeed' : IDL.Func([IDL.Nat], [], []),
  'getAllPillars' : IDL.Func([], [IDL.Vec(Pillar)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCollaborationRequests' : IDL.Func(
      [],
      [IDL.Vec(CollaborationRequest)],
      ['query'],
    ),
  'getFeaturedFeeds' : IDL.Func([], [IDL.Vec(FeedEntry)], ['query']),
  'getPathwayStats' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
      ['query'],
    ),
  'getPublicFeeds' : IDL.Func([], [IDL.Vec(FeedEntry)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'logPathwayInterest' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitCollaborationRequest' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'toggleFeatured' : IDL.Func([IDL.Nat], [], []),
  'updateFeed' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Bool, IDL.Bool],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Pillar = IDL.Record({
    'id' : IDL.Nat,
    'mandate' : IDL.Text,
    'operationalModel' : IDL.Text,
    'name' : IDL.Text,
    'strategicRole' : IDL.Text,
    'governanceNote' : IDL.Text,
    'initiatives' : IDL.Text,
    'futureDirection' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const CollaborationRequest = IDL.Record({
    'id' : IDL.Nat,
    'pathway' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const FeedEntry = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'domain' : IDL.Text,
    'summary' : IDL.Text,
    'isFeatured' : IDL.Bool,
    'timestamp' : IDL.Int,
    'isPublic' : IDL.Bool,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createFeed' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Bool, IDL.Bool],
        [],
        [],
      ),
    'deleteFeed' : IDL.Func([IDL.Nat], [], []),
    'getAllPillars' : IDL.Func([], [IDL.Vec(Pillar)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCollaborationRequests' : IDL.Func(
        [],
        [IDL.Vec(CollaborationRequest)],
        ['query'],
      ),
    'getFeaturedFeeds' : IDL.Func([], [IDL.Vec(FeedEntry)], ['query']),
    'getPathwayStats' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
        ['query'],
      ),
    'getPublicFeeds' : IDL.Func([], [IDL.Vec(FeedEntry)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'logPathwayInterest' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitCollaborationRequest' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'toggleFeatured' : IDL.Func([IDL.Nat], [], []),
    'updateFeed' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Bool, IDL.Bool],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };