/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CollaborationRequest {
  'id' : bigint,
  'pathway' : string,
  'name' : string,
  'email' : string,
  'message' : string,
  'timestamp' : bigint,
}
export interface FeedEntry {
  'id' : bigint,
  'title' : string,
  'domain' : string,
  'summary' : string,
  'isFeatured' : boolean,
  'timestamp' : bigint,
  'isPublic' : boolean,
}
export interface Pillar {
  'id' : bigint,
  'mandate' : string,
  'operationalModel' : string,
  'name' : string,
  'strategicRole' : string,
  'governanceNote' : string,
  'initiatives' : string,
  'futureDirection' : string,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createFeed' : ActorMethod<
    [string, string, string, boolean, boolean],
    undefined
  >,
  'deleteFeed' : ActorMethod<[bigint], undefined>,
  'getAllPillars' : ActorMethod<[], Array<Pillar>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCollaborationRequests' : ActorMethod<[], Array<CollaborationRequest>>,
  'getFeaturedFeeds' : ActorMethod<[], Array<FeedEntry>>,
  'getPathwayStats' : ActorMethod<[], Array<[string, bigint]>>,
  'getPublicFeeds' : ActorMethod<[], Array<FeedEntry>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'logPathwayInterest' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitCollaborationRequest' : ActorMethod<
    [string, string, string, string],
    undefined
  >,
  'toggleFeatured' : ActorMethod<[bigint], undefined>,
  'updateFeed' : ActorMethod<
    [bigint, string, string, string, boolean, boolean],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];