/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface ElpisCouncilMember {
    id: bigint;
    domain: string;
    name: string;
    role: string;
    biography: string;
    expertise: string;
    organization: string;
}
export interface HumanonPartner {
    id: bigint;
    name: string;
    description: string;
    sector: string;
}
export interface CollaborationRequest {
    id: bigint;
    pathway: string;
    name: string;
    email: string;
    message: string;
    timestamp: bigint;
}
export interface ElpisAnnouncement {
    id: bigint;
    title: string;
    publishedAt: bigint;
    summary: string;
    category: string;
    isPublic: boolean;
}
export interface Pillar {
    id: bigint;
    mandate: string;
    operationalModel: string;
    name: string;
    strategicRole: string;
    governanceNote: string;
    initiatives: string;
    futureDirection: string;
}
export interface HumanonMentor {
    id: bigint;
    domain: string;
    name: string;
    role: string;
    organization: string;
    profileUrl: string;
}
export interface HumanonProject {
    id: bigint;
    title: string;
    participantTeam: string;
    publishedAt: bigint;
    summary: string;
    researchDomain: string;
    mentorsInvolved: string;
    outcome: string;
}
export interface FeedEntry {
    id: bigint;
    title: string;
    domain: string;
    summary: string;
    isFeatured: boolean;
    timestamp: bigint;
    isPublic: boolean;
}
export interface ElpisGuidanceArea {
    id: bigint;
    domain: string;
    description: string;
    contribution: string;
}
export interface UserProfile {
    name: string;
}
export interface HumanonStats {
    participantsEnrolled: bigint;
    industryPartners: bigint;
    careerPlacements: bigint;
    countriesRepresented: bigint;
    projectsCompleted: bigint;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createElpisAnnouncement(title: string, summary: string, category: string, isPublic: boolean): Promise<void>;
    createElpisCouncilMember(name: string, domain: string, organization: string, role: string, biography: string, expertise: string): Promise<void>;
    createElpisGuidanceArea(domain: string, description: string, contribution: string): Promise<void>;
    createFeed(title: string, summary: string, domain: string, isPublic: boolean, isFeatured: boolean): Promise<void>;
    createHumanonMentor(name: string, domain: string, organization: string, role: string, profileUrl: string): Promise<void>;
    createHumanonPartner(name: string, sector: string, description: string): Promise<void>;
    createHumanonProject(title: string, researchDomain: string, participantTeam: string, summary: string, outcome: string, mentorsInvolved: string): Promise<void>;
    deleteElpisAnnouncement(id: bigint): Promise<void>;
    deleteElpisCouncilMember(id: bigint): Promise<void>;
    deleteElpisGuidanceArea(id: bigint): Promise<void>;
    deleteFeed(id: bigint): Promise<void>;
    deleteHumanonMentor(id: bigint): Promise<void>;
    deleteHumanonPartner(id: bigint): Promise<void>;
    deleteHumanonProject(id: bigint): Promise<void>;
    getAllElpisAnnouncements(): Promise<Array<ElpisAnnouncement>>;
    getAllPillars(): Promise<Array<Pillar>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCollaborationRequests(): Promise<Array<CollaborationRequest>>;
    getElpisAnnouncements(): Promise<Array<ElpisAnnouncement>>;
    getElpisCouncilMembers(): Promise<Array<ElpisCouncilMember>>;
    getElpisGuidanceAreas(): Promise<Array<ElpisGuidanceArea>>;
    getFeaturedFeeds(): Promise<Array<FeedEntry>>;
    getHumanonMentors(): Promise<Array<HumanonMentor>>;
    getHumanonPartners(): Promise<Array<HumanonPartner>>;
    getHumanonProjects(): Promise<Array<HumanonProject>>;
    getHumanonStats(): Promise<HumanonStats>;
    getPathwayStats(): Promise<Array<[string, bigint]>>;
    getPublicFeeds(): Promise<Array<FeedEntry>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    logPathwayInterest(pathway: string): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    submitCollaborationRequest(name: string, email: string, pathway: string, message: string): Promise<void>;
    toggleFeatured(id: bigint): Promise<void>;
    updateFeed(id: bigint, title: string, summary: string, domain: string, isPublic: boolean, isFeatured: boolean): Promise<void>;
    updateHumanonProject(id: bigint, title: string, researchDomain: string, participantTeam: string, summary: string, outcome: string, mentorsInvolved: string): Promise<void>;
    updateHumanonStats(participantsEnrolled: bigint, projectsCompleted: bigint, industryPartners: bigint, careerPlacements: bigint, countriesRepresented: bigint): Promise<void>;
}
import type { UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createElpisAnnouncement(arg0: string, arg1: string, arg2: string, arg3: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createElpisAnnouncement(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createElpisAnnouncement(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async createElpisCouncilMember(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createElpisCouncilMember(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createElpisCouncilMember(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async createElpisGuidanceArea(arg0: string, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createElpisGuidanceArea(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createElpisGuidanceArea(arg0, arg1, arg2);
            return result;
        }
    }
    async createFeed(arg0: string, arg1: string, arg2: string, arg3: boolean, arg4: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createFeed(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createFeed(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async createHumanonMentor(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createHumanonMentor(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createHumanonMentor(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async createHumanonPartner(arg0: string, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createHumanonPartner(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createHumanonPartner(arg0, arg1, arg2);
            return result;
        }
    }
    async createHumanonProject(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createHumanonProject(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createHumanonProject(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async deleteElpisAnnouncement(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteElpisAnnouncement(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteElpisAnnouncement(arg0);
            return result;
        }
    }
    async deleteElpisCouncilMember(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteElpisCouncilMember(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteElpisCouncilMember(arg0);
            return result;
        }
    }
    async deleteElpisGuidanceArea(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteElpisGuidanceArea(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteElpisGuidanceArea(arg0);
            return result;
        }
    }
    async deleteFeed(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteFeed(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteFeed(arg0);
            return result;
        }
    }
    async deleteHumanonMentor(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteHumanonMentor(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteHumanonMentor(arg0);
            return result;
        }
    }
    async deleteHumanonPartner(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteHumanonPartner(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteHumanonPartner(arg0);
            return result;
        }
    }
    async deleteHumanonProject(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteHumanonProject(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteHumanonProject(arg0);
            return result;
        }
    }
    async getAllElpisAnnouncements(): Promise<Array<ElpisAnnouncement>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllElpisAnnouncements();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllElpisAnnouncements();
            return result;
        }
    }
    async getAllPillars(): Promise<Array<Pillar>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPillars();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPillars();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCollaborationRequests(): Promise<Array<CollaborationRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCollaborationRequests();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCollaborationRequests();
            return result;
        }
    }
    async getElpisAnnouncements(): Promise<Array<ElpisAnnouncement>> {
        if (this.processError) {
            try {
                const result = await this.actor.getElpisAnnouncements();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getElpisAnnouncements();
            return result;
        }
    }
    async getElpisCouncilMembers(): Promise<Array<ElpisCouncilMember>> {
        if (this.processError) {
            try {
                const result = await this.actor.getElpisCouncilMembers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getElpisCouncilMembers();
            return result;
        }
    }
    async getElpisGuidanceAreas(): Promise<Array<ElpisGuidanceArea>> {
        if (this.processError) {
            try {
                const result = await this.actor.getElpisGuidanceAreas();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getElpisGuidanceAreas();
            return result;
        }
    }
    async getFeaturedFeeds(): Promise<Array<FeedEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFeaturedFeeds();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFeaturedFeeds();
            return result;
        }
    }
    async getHumanonMentors(): Promise<Array<HumanonMentor>> {
        if (this.processError) {
            try {
                const result = await this.actor.getHumanonMentors();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHumanonMentors();
            return result;
        }
    }
    async getHumanonPartners(): Promise<Array<HumanonPartner>> {
        if (this.processError) {
            try {
                const result = await this.actor.getHumanonPartners();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHumanonPartners();
            return result;
        }
    }
    async getHumanonProjects(): Promise<Array<HumanonProject>> {
        if (this.processError) {
            try {
                const result = await this.actor.getHumanonProjects();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHumanonProjects();
            return result;
        }
    }
    async getHumanonStats(): Promise<HumanonStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getHumanonStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHumanonStats();
            return result;
        }
    }
    async getPathwayStats(): Promise<Array<[string, bigint]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPathwayStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPathwayStats();
            return result;
        }
    }
    async getPublicFeeds(): Promise<Array<FeedEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPublicFeeds();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPublicFeeds();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async logPathwayInterest(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.logPathwayInterest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.logPathwayInterest(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async submitCollaborationRequest(arg0: string, arg1: string, arg2: string, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitCollaborationRequest(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitCollaborationRequest(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async toggleFeatured(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleFeatured(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleFeatured(arg0);
            return result;
        }
    }
    async updateFeed(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: boolean, arg5: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateFeed(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateFeed(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async updateHumanonProject(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string, arg6: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateHumanonProject(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateHumanonProject(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return result;
        }
    }
    async updateHumanonStats(arg0: bigint, arg1: bigint, arg2: bigint, arg3: bigint, arg4: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateHumanonStats(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateHumanonStats(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
}
function from_candid_UserRole_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
